repos:
  # AWS Key Detection
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: check-added-large-files
        args: ['--maxkb=500']  # limits maximal file size

  # Formatting
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-docstrings]



name: COS397_Homework5_PenUltimate 

on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: flake8 and black
        uses: py-actions/flake8-black@v1.2.0
        
        name: max file size 500kb
        with:
          max-file-size: 500